### ISSUE TITLE
ICO server or authentication process seems no more working since official Homey V5.0.0

### ISSUE THREAD

**Issue by alechenne** [edwinvdpol/com.ondilo.ico#1]
Device was succesfully installed on beta version oh Homey 5.0 and was working. Since a week (since I installed the last and official version of Homey firmware 5.0.0), it displayed a red "!". Restarting the app don't solve the issue. Trying to do the "repair" process also isn't working -> it access to the web authentication page of ondillo (https://interop.ondilo.com/oauth2) but nothing is displayed. Server seems no more working.

**Comment by edwinvdpol** [comment]
Thank you for reaching out. I'm afraid the Ondilo API is down.

See the [Ondilo forum thread](https://community.athom.com/t/ico-pool-spa/37536/2?u=evdpol) for more information.

**Comment by alechenne** [comment]
> Thank you for reaching out. I'm afraid the Ondilo API is down.
> 
> See the [Ondilo forum thread](https://community.athom.com/t/ico-pool-spa/37536/2?u=evdpol) for more information.

I post an issue on their support last week-end and they replied to me that the server is in maintenance. On March 1st the service is now on. Case is closed. Thanks.

**Comment by edwinvdpol** [comment]
Thanks for the update @alechenne!

Closed.
